name: Build

on: [ push ]

jobs:
  build-server:
    name: Build smart contract & server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Show NodeJS & NPM versions
        run: node --version && npm --version

      - name: Install Server Dependencies
        run: cd server && npm ci

      - name: Install Truffle
        run: npm install truffle -g

      - name: Install Blockchain Dependencies
        run: cd blockchain && npm ci

      - name: Run Blockchain tests & Generate coverage
        run: cd blockchain && truffle run coverage

      - name: Send Blockchain coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./blockchain/coverage/lcov.info

      - name: Generate contract types
        run: cd blockchain && truffle compile && npm run types

      - name: Run Server unit tests and generate coverage report
        run: cd server && npm run test:coverage

      - name: Run Server e2e tests and generate coverage report
        run: cd server && npm run test:e2e:coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}